### ISSUE TITLE
Circle animation is blinking when loaded for the first time

### ISSUE THREAD

**Issue by StevenMasini** [tienph6m/react-native-animated-spinkit#1]
@tienph6m First thank you for this great alternative to `react-native-spinkit`.

I integrated your library today and noticed that when loading `<Circle />` the first apparition won't be animated but instead will be blinking.

### Example

![spinkit-blink 2019-12-03 17_37_22](https://user-images.githubusercontent.com/1907562/70038684-9fc5d480-15f3-11ea-8356-23ed8c838805.gif)

**Comment by tienph6m** [comment]
Hi @StevenMasini,
Could you elaborate a bit more? Did you have this issue on Android or iOS? Did it run correctly after the first time?
Also, I've just published v1.2.0, please try that out and let me know if it fixes the issue.

**Comment by phamfoo** [comment]
Hi @StevenMasini,
I've just published `1.3.0-beta.0`. I only updated the `Circle` component for now. Please try that out and let me know if it fixes the issue. 
~~Could you elaborate a bit more? Did it run correctly after the first time? Does this happen when you put the spinner in a blank screen or in a real app with other components?
Also, I've just published v1.2.0, please try that out and let me know if it fixes the issue.~~

**Comment by StevenMasini** [comment]
@tienph6m I will give it a try, thanks for your answer 👍 
I am confident in your implementation, I am sure that something you can tackle down easily.

After the component appeared once, it does not reproduce, just the first launch is blinking.

**Comment by phamfoo** [comment]
Thanks man ;) 1.3.0 is ready. I'll publish it as soon as you confirm that the beta version fixes the issue.

**Comment by StevenMasini** [comment]
I am on it, hold on testing right now.

**Comment by StevenMasini** [comment]
@tienph6m I confirm, it's fixed with `1.3.0-beta.0`! 
Thank you 👍

**Comment by phamfoo** [comment]
Thanks 👍 1.3.0 is up 🚀
