### ISSUE TITLE
re-write this package to react native reanimated v2

### ISSUE THREAD

**Issue by Ppang0405** [tienph6m/react-native-animated-spinkit#14]

**Comment by tienphaw** [comment]
At the moment [performance is not great when animating with multiple shared values](https://github.com/software-mansion/react-native-reanimated/discussions/1632#discussioncomment-308223). I'll probably publish another package that uses reanimated 2 in the future, this one will stick with Animated though.

**Comment by tienphaw** [comment]
At the moment [performance is not great when animating using multiple shared values](https://github.com/software-mansion/react-native-reanimated/discussions/1632). I'll probably publish another package that uses reanimated 2 in the future, this one will stick with Animated though.

**Comment by phamfoo** [comment]
At the moment [performance is not great when animating with multiple shared values](https://github.com/software-mansion/react-native-reanimated/discussions/1632). I'll probably publish another package that uses reanimated 2 in the future, this one will stick with Animated though.
