### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSpinkit" was not found in the UIManager.

### ISSUE THREAD

**Issue by sayan-avantai** [tienph6m/react-native-animated-spinkit#27]
"react-native": "0.74.3",
"react-native-animated-spinkit": "^1.5.2",
"react-native-dynamic-search-bar": "^2.0.2",
"@freakycoder/react-native-bounceable": "^1.0.3",

**Comment by phamfoo** [comment]
This error doesn't come from this library, looks like you're using `react-native-spinkit` somewhere in your project.
