### ISSUE TITLE
Some part of the animation is stuck?

### ISSUE THREAD

**Issue by xmflsct** [tienph6m/react-native-animated-spinkit#8]
First of all, thanks for the library to be used with Expo!

I found a weird situation. I am using this library within a customized button. Herewith a simple example of the code.
Basically it is a button that can take either text or an icon. And while the button is pressed and being loaded with data, the spinner will show up instaed of the content inside.

```
const Button = ({
  type = 'icon',
  content,
  loading,
  disabled,
  onPress
}) => {

  const loadingSpinkit = useMemo(
    () => (
      <View style={{ position: 'absolute' }}>
        <Chase
          size={20}
          color='black'
        />
      </View>
    ),
    []
  )

  const children = useMemo(() => {
    switch (type) {
      case 'icon':
        return (
          <>
            <Icon name={content} />
            {loading && loadingSpinkit}
          </>
        )
      case 'text':
        return (
          <>
            <Text children={content} />
            {loading && loadingSpinkit}
          </>
        )
    }
  }, [loading, disabled])

  return (
    <Pressable
      onPress={onPress}
      children={children}
      disabled={disabled || loading}
    />
  )
}

export default Button
```

When this component is first being loaded, the animation is fine. But after each press, the spinner shows but some part of it will stuck. See image below. I tried several types and all of them have some parts stuck. Is there a reason why?

![Screen Shot 2021-01-10 at 15 22 59](https://user-images.githubusercontent.com/292204/104125748-1554b600-5359-11eb-89f1-adc6753006f5.png)

**Comment by phamfoo** [comment]
Can you create a github repo or a [snack](https://snack.expo.io/) for me to look at @xmflsct?

**Comment by xmflsct** [comment]
I dig around a bit more, now I know it is `"react-native-reanimated": "2.0.0-rc.0"` causing the issue.
I get a snack but that doesn't allow installing reanimated 2 but I have tried it on my local machine.

So with all freshly rendered spinkit, it works fine but when it is re-rendered, then it somehow breaks.

**Comment by phamfoo** [comment]
Do you have Turbo Modules enabled in your expo project? You might want to disable it as Animated doesn't play well with Turbo Modules. If you're using Expo SDK 40, try removing the `experiments.turboModules` key in your `app.json`.

**Comment by xmflsct** [comment]
Thanks, exactly that is the issue. Somehow I got an impression that `turbo` has to be on with expo 40 + reanimated 2. But I look at the installation docs again, it is not mentioned anywhere.
